name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/apache2-server:latest
    - name: Push the Docker Image
      run: docker push ghcr.io/${{ github.repository }}/apache2-server:latest

